
stages:
  - test
  - deploy
  # - validate
  - notify

validate:
  image: dockerhub.cisco.com/as-dev-docker-local/cisco/cleur21_semops21:v1
  stage: test
  script:
    - echo TODO

commit_prod:
  image: dockerhub.cisco.com/as-dev-docker-local/cisco/cleur21_semops21:v1
  stage: deploy
  # only:
  #   - master
  script:
    - python scripts/dnac_templ.py --debug

# test:
#   image: ${DOCKER_REPO}/${RUNNER_IMAGE}
#   stage: test
#   script:
#     - echo 'test to be done'

# last step in the pipeline to report status
notify_success:
 image: ${DOCKER_REPO}/${RUNNER_IMAGE}
 stage: notify
 when: on_success
 script:
   # assumes teams token is provided in environment variable
   # WEBEX_API_NOTIFICATION_TOKEN
   - python scripts/notify.py "✅ Pipeline completed successfully ($CI_JOB_URL)"

notify_failure:
 image: ${DOCKER_REPO}/${RUNNER_IMAGE}
 stage: notify
 when: on_failure
 script:
   # assumes teams token is provided in environment variable
   # WEBEX_API_NOTIFICATION_TOKEN
   - python scripts/notify.py "❌ Pipeline failed ($CI_JOB_URL)"
