# vars in gitlab-ci env:
# RUNNER_IMAGE: dockerhub.cisco.com/as-dev-docker-local/cisco/cleur21_semops21:v1
stages:
  - test
  - deploy
  # - validate
  - notify

validate:
  image: ${RUNNER_IMAGE}
  stage: test
  script:
    - echo TODO

# commit stage, use different configs depending if we run in master
# or in branches
commit_prod:
  image: ${RUNNER_IMAGE}
  stage: deploy
  only:
    - master
  artifacts:
    paths:
      - results.json
  script:
    - python scripts/dnac_templ.py --results results.json --debug

commit_preprod:
  image: ${RUNNER_IMAGE}
  stage: deploy
  only:
    - branches
  artifacts:
    paths:
      - results.json
  script:
    - python scripts/dnac_templ.py --config scripts/config-preprod.yaml --results results.json --debug

# test:
#   image: ${DOCKER_REPO}/${RUNNER_IMAGE}
#   stage: test
#   script:
#     - echo 'test to be done'

# last step in the pipeline to report status
# we need multiple steps here as we want/need to differentiate between success
# and failures and between master and non-master branches
notify_success_master:
  image: ${RUNNER_IMAGE}
  stage: notify
  only:
    - master
  when: on_success
  script:
    - python scripts/notify.py  --results results.json "✅ Pipeline on branch $CI_BUILD_REF_NAME completed successfully ($CI_PIPELINE_URL)"

notify_failure_master:
  image: ${RUNNER_IMAGE}
  stage: notify
  when: on_failure
  only:
    - master
  script:
    - python scripts/notify.py  --results results.json "❌ Pipeline on branch $CI_BUILD_REF_NAME failed ($CI_PIPELINE_URL)"

# send branch pipeline results only to the developer
notify_success_branches:
  image: ${RUNNER_IMAGE}
  stage: notify
  only:
    - branches
  when: on_success
  script:
    - python scripts/notify.py --person $GITLAB_USER_EMAIL --results results.json "✅ Pipeline on branch $CI_BUILD_REF_NAME completed successfully ($CI_PIPELINE_URL)"

notify_failure_branches:
  image: ${RUNNER_IMAGE}
  stage: notify
  when: on_failure
  only:
    - branches
  script:
    - python scripts/notify.py --person $GITLAB_USER_EMAIL --results results.json "❌ Pipeline on branch $CI_BUILD_REF_NAME failed ($CI_PIPELINE_URL)"
